name: Deploy on Self-hosted Runner

on:
  push:
    branches:
      - main   # or your default branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull and deploy latest code
        run: |
          cd /home/ec2-user/ballurh-website
          git pull
          docker-compose --env-file .env up -d --build
